language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.11
  - "1.10"

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip

